#
#       MAKEFILE FOR RAND "LA" LINE-ACCESS I/O PACKAGE
#
ARFLAGS = -r
# CFLAGS = -O -I. -I../ff3 -I../include
CFLAGS = -I. -I../ff3 -I../include -g

ALL=libla.a
SRCS=   laabort.c laadv.c   laalign.c lablank.c labreak.c labsize.c \
	lacfile.c laclose.c ladeb.c   laerr.c   lafrpl.c \
	laint.c   lalcnt.c  lalcol.c  lalcopy.c laldel.c  lalflush.c \
	lalget.c  lalink.c  lalins.c  lalpnt.c  lalrpl.c  lalrsize.c \
	lalseek.c lalwsize.c laopen.c laother.c

OBJS=   laabort.o laadv.o   laalign.o lablank.o labreak.o labsize.o \
	lacfile.o laclose.o ladeb.o   laerr.o   lafrpl.o \
	laint.o   lalcnt.o  lalcol.o  lalcopy.o laldel.o  lalflush.o \
	lalget.o  lalink.o  lalins.o  lalpnt.o  lalrpl.o  lalrsize.o \
	lalseek.o lalwsize.o laopen.o laother.o

$(ALL) : $(OBJS)
	$(AR) $(ARFLAGS) $@ $(OBJS)

clean:
	rm -f $(OBJS) $(ALL)  ,* .e?[1-9] .e?[1-9].* core *.bak *.BAK *~ \#*

depend:
	makedepend -- $(CFLAGS) -- $(SRCS)

# DO NOT DELETE THIS LINE -- make depend depends on it.

laabort.o: la.local.h ../include/c_env.h ../include/localenv.h
laabort.o: /usr/include/stdio.h /usr/include/features.h
laabort.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
laabort.o: 
laabort.o: /usr/include/bits/types.h /usr/include/libio.h
laabort.o: /usr/include/_G_config.h /usr/include/wchar.h
laabort.o: /usr/include/bits/wchar.h /usr/include/gconv.h
laabort.o: 
laabort.o: /usr/include/bits/stdio_lim.h /usr/include/string.h
laabort.o: /usr/include/sys/types.h /usr/include/time.h la.h ../ff3/ff.h
laabort.o: /usr/include/limits.h
laabort.o: 
laadv.o: la.local.h ../include/c_env.h ../include/localenv.h
laadv.o: /usr/include/stdio.h /usr/include/features.h
laadv.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
laadv.o: /usr/include/bits/types.h /usr/include/libio.h
laadv.o: /usr/include/_G_config.h /usr/include/wchar.h
laadv.o: /usr/include/bits/wchar.h /usr/include/gconv.h
laadv.o: 
laadv.o: /usr/include/bits/stdio_lim.h /usr/include/string.h
laadv.o: /usr/include/sys/types.h /usr/include/time.h la.h ../ff3/ff.h
laadv.o: /usr/include/limits.h
laadv.o: 
laalign.o: la.local.h ../include/c_env.h ../include/localenv.h
laalign.o: /usr/include/stdio.h /usr/include/features.h
laalign.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
laalign.o: 
laalign.o: /usr/include/bits/types.h /usr/include/libio.h
laalign.o: /usr/include/_G_config.h /usr/include/wchar.h
laalign.o: /usr/include/bits/wchar.h /usr/include/gconv.h
laalign.o: 
laalign.o: /usr/include/bits/stdio_lim.h /usr/include/string.h
laalign.o: /usr/include/sys/types.h /usr/include/time.h la.h ../ff3/ff.h
laalign.o: /usr/include/limits.h
laalign.o: 
lablank.o: la.local.h ../include/c_env.h ../include/localenv.h
lablank.o: /usr/include/stdio.h /usr/include/features.h
lablank.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lablank.o: 
lablank.o: /usr/include/bits/types.h /usr/include/libio.h
lablank.o: /usr/include/_G_config.h /usr/include/wchar.h
lablank.o: /usr/include/bits/wchar.h /usr/include/gconv.h
lablank.o: 
lablank.o: /usr/include/bits/stdio_lim.h /usr/include/string.h
lablank.o: /usr/include/sys/types.h /usr/include/time.h la.h ../ff3/ff.h
lablank.o: /usr/include/limits.h
lablank.o: 
labreak.o: la.local.h ../include/c_env.h ../include/localenv.h
labreak.o: /usr/include/stdio.h /usr/include/features.h
labreak.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
labreak.o: 
labreak.o: /usr/include/bits/types.h /usr/include/libio.h
labreak.o: /usr/include/_G_config.h /usr/include/wchar.h
labreak.o: /usr/include/bits/wchar.h /usr/include/gconv.h
labreak.o: 
labreak.o: /usr/include/bits/stdio_lim.h /usr/include/string.h
labreak.o: /usr/include/sys/types.h /usr/include/time.h la.h ../ff3/ff.h
labreak.o: /usr/include/limits.h
labreak.o: 
labsize.o: la.local.h ../include/c_env.h ../include/localenv.h
labsize.o: /usr/include/stdio.h /usr/include/features.h
labsize.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
labsize.o: 
labsize.o: /usr/include/bits/types.h /usr/include/libio.h
labsize.o: /usr/include/_G_config.h /usr/include/wchar.h
labsize.o: /usr/include/bits/wchar.h /usr/include/gconv.h
labsize.o: 
labsize.o: /usr/include/bits/stdio_lim.h /usr/include/string.h
labsize.o: /usr/include/sys/types.h /usr/include/time.h la.h ../ff3/ff.h
labsize.o: /usr/include/limits.h
labsize.o: 
lacfile.o: la.local.h ../include/c_env.h ../include/localenv.h
lacfile.o: /usr/include/stdio.h /usr/include/features.h
lacfile.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lacfile.o: 
lacfile.o: /usr/include/bits/types.h /usr/include/libio.h
lacfile.o: /usr/include/_G_config.h /usr/include/wchar.h
lacfile.o: /usr/include/bits/wchar.h /usr/include/gconv.h
lacfile.o: 
lacfile.o: /usr/include/bits/stdio_lim.h /usr/include/string.h
lacfile.o: /usr/include/sys/types.h /usr/include/time.h la.h ../ff3/ff.h
lacfile.o: /usr/include/limits.h
lacfile.o: 
laclose.o: la.local.h ../include/c_env.h ../include/localenv.h
laclose.o: /usr/include/stdio.h /usr/include/features.h
laclose.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
laclose.o: 
laclose.o: /usr/include/bits/types.h /usr/include/libio.h
laclose.o: /usr/include/_G_config.h /usr/include/wchar.h
laclose.o: /usr/include/bits/wchar.h /usr/include/gconv.h
laclose.o: 
laclose.o: /usr/include/bits/stdio_lim.h /usr/include/string.h
laclose.o: /usr/include/sys/types.h /usr/include/time.h la.h ../ff3/ff.h
laclose.o: /usr/include/limits.h
laclose.o: 
ladeb.o: la.local.h ../include/c_env.h ../include/localenv.h
ladeb.o: /usr/include/stdio.h /usr/include/features.h
ladeb.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
ladeb.o: 
ladeb.o: /usr/include/bits/types.h /usr/include/libio.h
ladeb.o: /usr/include/_G_config.h /usr/include/wchar.h
ladeb.o: /usr/include/bits/wchar.h /usr/include/gconv.h
ladeb.o: 
ladeb.o: /usr/include/bits/stdio_lim.h /usr/include/string.h
ladeb.o: /usr/include/sys/types.h /usr/include/time.h la.h ../ff3/ff.h
ladeb.o: /usr/include/limits.h
ladeb.o: 
laerr.o: la.local.h ../include/c_env.h ../include/localenv.h
laerr.o: /usr/include/stdio.h /usr/include/features.h
laerr.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
laerr.o: 
laerr.o: /usr/include/bits/types.h /usr/include/libio.h
laerr.o: /usr/include/_G_config.h /usr/include/wchar.h
laerr.o: /usr/include/bits/wchar.h /usr/include/gconv.h
laerr.o: 
laerr.o: /usr/include/bits/stdio_lim.h /usr/include/string.h
laerr.o: /usr/include/sys/types.h /usr/include/time.h la.h ../ff3/ff.h
laerr.o: /usr/include/limits.h
laerr.o: 
lafrpl.o: la.local.h ../include/c_env.h ../include/localenv.h
lafrpl.o: /usr/include/stdio.h /usr/include/features.h
lafrpl.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lafrpl.o: 
lafrpl.o: /usr/include/bits/types.h /usr/include/libio.h
lafrpl.o: /usr/include/_G_config.h /usr/include/wchar.h
lafrpl.o: /usr/include/bits/wchar.h /usr/include/gconv.h
lafrpl.o: 
lafrpl.o: /usr/include/bits/stdio_lim.h /usr/include/string.h
lafrpl.o: /usr/include/sys/types.h /usr/include/time.h la.h ../ff3/ff.h
lafrpl.o: /usr/include/limits.h
lafrpl.o: 
lalcnt.o: la.local.h ../include/c_env.h ../include/localenv.h
lalcnt.o: /usr/include/stdio.h /usr/include/features.h
lalcnt.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lalcnt.o: 
lalcnt.o: /usr/include/bits/types.h /usr/include/libio.h
lalcnt.o: /usr/include/_G_config.h /usr/include/wchar.h
lalcnt.o: /usr/include/bits/wchar.h /usr/include/gconv.h
lalcnt.o: 
lalcnt.o: /usr/include/bits/stdio_lim.h /usr/include/string.h
lalcnt.o: /usr/include/sys/types.h /usr/include/time.h la.h ../ff3/ff.h
lalcnt.o: /usr/include/limits.h
lalcnt.o: 
lalcol.o: la.local.h ../include/c_env.h ../include/localenv.h
lalcol.o: /usr/include/stdio.h /usr/include/features.h
lalcol.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lalcol.o: 
lalcol.o: /usr/include/bits/types.h /usr/include/libio.h
lalcol.o: /usr/include/_G_config.h /usr/include/wchar.h
lalcol.o: /usr/include/bits/wchar.h /usr/include/gconv.h
lalcol.o: 
lalcol.o: /usr/include/bits/stdio_lim.h /usr/include/string.h
lalcol.o: /usr/include/sys/types.h /usr/include/time.h la.h ../ff3/ff.h
lalcol.o: /usr/include/limits.h
lalcol.o: 
lalcopy.o: la.local.h ../include/c_env.h ../include/localenv.h
lalcopy.o: /usr/include/stdio.h /usr/include/features.h
lalcopy.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lalcopy.o: 
lalcopy.o: /usr/include/bits/types.h /usr/include/libio.h
lalcopy.o: /usr/include/_G_config.h /usr/include/wchar.h
lalcopy.o: /usr/include/bits/wchar.h /usr/include/gconv.h
lalcopy.o: 
lalcopy.o: /usr/include/bits/stdio_lim.h /usr/include/string.h
lalcopy.o: /usr/include/sys/types.h /usr/include/time.h la.h ../ff3/ff.h
lalcopy.o: /usr/include/limits.h
laldel.o: la.local.h ../include/c_env.h ../include/localenv.h
laldel.o: /usr/include/stdio.h /usr/include/features.h
laldel.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
laldel.o: /usr/include/bits/types.h /usr/include/libio.h
laldel.o: /usr/include/_G_config.h /usr/include/wchar.h
laldel.o: /usr/include/bits/wchar.h /usr/include/gconv.h
laldel.o: /usr/include/bits/stdio_lim.h /usr/include/string.h
laldel.o: /usr/include/sys/types.h /usr/include/time.h la.h ../ff3/ff.h
laldel.o: /usr/include/limits.h
lalflush.o: la.local.h ../include/c_env.h ../include/localenv.h
lalflush.o: /usr/include/stdio.h /usr/include/features.h
lalflush.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lalflush.o: /usr/include/bits/types.h /usr/include/libio.h
lalflush.o: /usr/include/_G_config.h /usr/include/wchar.h
lalflush.o: /usr/include/bits/wchar.h /usr/include/gconv.h
lalflush.o: /usr/include/bits/stdio_lim.h /usr/include/string.h
lalflush.o: /usr/include/sys/types.h /usr/include/time.h la.h ../ff3/ff.h
lalflush.o: /usr/include/limits.h
lalflush.o: /usr/include/signal.h /usr/include/bits/sigset.h
lalflush.o: /usr/include/bits/signum.h
lalget.o: la.local.h ../include/c_env.h ../include/localenv.h
lalget.o: /usr/include/stdio.h /usr/include/features.h
lalget.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lalget.o: /usr/include/bits/types.h /usr/include/libio.h
lalget.o: /usr/include/_G_config.h /usr/include/wchar.h
lalget.o: /usr/include/bits/wchar.h /usr/include/gconv.h
lalget.o: /usr/include/bits/stdio_lim.h /usr/include/string.h
lalget.o: /usr/include/sys/types.h /usr/include/time.h la.h ../ff3/ff.h
lalget.o: /usr/include/limits.h
lalink.o: la.local.h ../include/c_env.h ../include/localenv.h
lalink.o: /usr/include/stdio.h /usr/include/features.h
lalink.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lalink.o: /usr/include/bits/types.h /usr/include/libio.h
lalink.o: /usr/include/_G_config.h /usr/include/wchar.h
lalink.o: /usr/include/bits/wchar.h /usr/include/gconv.h
lalink.o: /usr/include/bits/stdio_lim.h /usr/include/string.h
lalink.o: /usr/include/sys/types.h /usr/include/time.h la.h ../ff3/ff.h
lalink.o: /usr/include/limits.h
lalins.o: la.local.h ../include/c_env.h ../include/localenv.h
lalins.o: /usr/include/stdio.h /usr/include/features.h
lalins.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lalins.o: /usr/include/bits/types.h /usr/include/libio.h
lalins.o: /usr/include/_G_config.h /usr/include/wchar.h
lalins.o: /usr/include/bits/wchar.h /usr/include/gconv.h
lalins.o: /usr/include/bits/stdio_lim.h /usr/include/string.h
lalins.o: /usr/include/sys/types.h /usr/include/time.h la.h ../ff3/ff.h
lalins.o: /usr/include/limits.h
lalpnt.o: la.local.h ../include/c_env.h ../include/localenv.h
lalpnt.o: /usr/include/stdio.h /usr/include/features.h
lalpnt.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lalpnt.o: /usr/include/bits/types.h /usr/include/libio.h
lalpnt.o: /usr/include/_G_config.h /usr/include/wchar.h
lalpnt.o: /usr/include/bits/wchar.h /usr/include/gconv.h
lalpnt.o: /usr/include/bits/stdio_lim.h /usr/include/string.h
lalpnt.o: /usr/include/sys/types.h /usr/include/time.h la.h ../ff3/ff.h
lalpnt.o: /usr/include/limits.h
lalrpl.o: la.local.h ../include/c_env.h ../include/localenv.h
lalrpl.o: /usr/include/stdio.h /usr/include/features.h
lalrpl.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lalrpl.o: /usr/include/bits/types.h /usr/include/libio.h
lalrpl.o: /usr/include/_G_config.h /usr/include/wchar.h
lalrpl.o: /usr/include/bits/wchar.h /usr/include/gconv.h
lalrpl.o: /usr/include/bits/stdio_lim.h /usr/include/string.h
lalrpl.o: /usr/include/sys/types.h /usr/include/time.h la.h ../ff3/ff.h
lalrpl.o: /usr/include/limits.h
lalrsize.o: la.local.h ../include/c_env.h ../include/localenv.h
lalrsize.o: /usr/include/stdio.h /usr/include/features.h
lalrsize.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lalrsize.o: /usr/include/bits/types.h /usr/include/libio.h
lalrsize.o: /usr/include/_G_config.h /usr/include/wchar.h
lalrsize.o: /usr/include/bits/wchar.h /usr/include/gconv.h
lalrsize.o: /usr/include/bits/stdio_lim.h /usr/include/string.h
lalrsize.o: /usr/include/sys/types.h /usr/include/time.h la.h ../ff3/ff.h
lalrsize.o: /usr/include/limits.h
lalseek.o: la.local.h ../include/c_env.h ../include/localenv.h
lalseek.o: /usr/include/stdio.h /usr/include/features.h
lalseek.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lalseek.o: /usr/include/bits/types.h /usr/include/libio.h
lalseek.o: /usr/include/_G_config.h /usr/include/wchar.h
lalseek.o: /usr/include/bits/wchar.h /usr/include/gconv.h
lalseek.o: /usr/include/bits/stdio_lim.h /usr/include/string.h
lalseek.o: /usr/include/sys/types.h /usr/include/time.h la.h ../ff3/ff.h
lalseek.o: /usr/include/limits.h
lalwsize.o: la.local.h ../include/c_env.h ../include/localenv.h
lalwsize.o: /usr/include/stdio.h /usr/include/features.h
lalwsize.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lalwsize.o: /usr/include/bits/types.h /usr/include/libio.h
lalwsize.o: /usr/include/_G_config.h /usr/include/wchar.h
lalwsize.o: /usr/include/bits/wchar.h /usr/include/gconv.h
lalwsize.o: /usr/include/bits/stdio_lim.h /usr/include/string.h
lalwsize.o: /usr/include/sys/types.h /usr/include/time.h la.h ../ff3/ff.h
lalwsize.o: /usr/include/limits.h
laopen.o: la.local.h ../include/c_env.h ../include/localenv.h
laopen.o: /usr/include/stdio.h /usr/include/features.h
laopen.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
laopen.o: /usr/include/bits/types.h /usr/include/libio.h
laopen.o: /usr/include/_G_config.h /usr/include/wchar.h
laopen.o: /usr/include/bits/wchar.h /usr/include/gconv.h
laopen.o: /usr/include/bits/stdio_lim.h /usr/include/string.h
laopen.o: /usr/include/sys/types.h /usr/include/time.h la.h ../ff3/ff.h
laopen.o: /usr/include/limits.h
laopen.o: /usr/include/sys/stat.h /usr/include/bits/stat.h
laopen.o: /usr/include/sys/resource.h /usr/include/bits/resource.h
laopen.o: /usr/include/bits/time.h
laother.o: la.local.h ../include/c_env.h ../include/localenv.h
laother.o: /usr/include/stdio.h /usr/include/features.h
laother.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
laother.o: /usr/include/bits/types.h /usr/include/libio.h
laother.o: /usr/include/_G_config.h /usr/include/wchar.h
laother.o: /usr/include/bits/wchar.h /usr/include/gconv.h
laother.o: /usr/include/bits/stdio_lim.h /usr/include/string.h
laother.o: /usr/include/sys/types.h /usr/include/time.h la.h ../ff3/ff.h
laother.o: /usr/include/limits.h
