#ifdef COMMENT
	Copyright abandoned, 1983, The Rand Corporation
#endif

Small command ();
Small gotocmd ();
Small doupdate ();
Scols tabright ();
Scols tableft ();
Small areacmd ();
Small splitmark ();
Small splitlines ();
Small joinmark ();
char * copy ();
Flag multlinks ();
Flag fmultlinks ();
Fn hvname ();
Fn hvoldname ();
Fn hvdelname ();
Flag putline ();
Short dechars ();
Flag extend ();
Nlines lincnt ();
Small print ();
Small filter ();
Small filtmark ();
Small filtlines ();
Small run ();
Small runlines ();
Flag dowait ();
Flag receive ();
Nlines topmark ();
Nlines leftmark ();
Flag gtumark ();
Small exchmark ();
Small name ();
Small delete ();
Flag dotdot ();
Small printchar ();
Small getpartype ();
char * getword ();
Small scanopts ();
Small getopteq ();
Small doeq ();
Small eexit ();
Flag endit ();
Flag savestate ();
char * getmypath ();
char * gsalloc ();
char * salloc ();
char * append ();
char * s2i ();
char * itoa();
Flag mv ();
Flag okwrite ();
Small filecopy ();
Small replace ();
Small dsplsearch ();
Small strsearch ();
Ncols skeylen ();
Small save ();
Flag savefile ();
Small movew ();
Small movep ();
Small movewin ();
unsigned Short getkey ();
static unsigned Short read2 ();
Flag dintrup ();
Flag la_int();
Flag sintrup ();
char * pkarg ();
Small dotab ();
Small dotabs ();
Small getptabs ();
Small tabfile ();
Flag gettabs ();
Small use ();
Small editfile ();
Fn getnxfn ();
